name: Build SourceMod Extension

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    #runs-on: ubuntu-latest
    ###################################################################
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ###################################################
        #os: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          #sudo apt-get install -y python3 python3-pip git g++ make
          sudo apt-get install -y python3 python3-pip git clang g++-multilib
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Install dependencies (Windows only)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip

      - name: Clone AMBuild
        run: |
          git clone https://github.com/alliedmodders/ambuild.git

      - name: Install AMBuild (Linux)
        if: runner.os == 'Linux'
        run: |
          pip3 install ./ambuild

      - name: Install AMBuild (Windows)
        if: runner.os == 'Windows'
        run: |
          cd ambuild
          python setup.py install

      - name: Clone SDKs
        run: |
          #git clone --depth 1 --recursive https://github.com/alliedmodders/metamod-source.git metamod
          #git clone --depth 1 --recursive https://github.com/alliedmodders/sourcemod.git sourcemod
          #git clone --depth 1 --branch css https://github.com/alliedmodders/hl2sdk.git hl2sdk-css
          #
          git clone --depth 1 --recursive https://github.com/alliedmodders/metamod-source.git metamod
          git clone --depth 1 --recursive https://github.com/alliedmodders/sourcemod.git sourcemod
          git clone --depth 1 --recursive --branch 1.10-dev https://github.com/alliedmodders/metamod-source.git metamod_1_10
          git clone --depth 1 --recursive --branch 1.10-dev https://github.com/alliedmodders/sourcemod.git sourcemod_1_10
          git clone --depth 1 --branch css https://github.com/alliedmodders/hl2sdk.git hl2sdk-css
          git clone --depth 1 --branch episode1 https://github.com/alliedmodders/hl2sdk.git hl2sdk-episode1

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build extension (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir build
          cd build
          #python3 ../configure.py --sdks css --hl2sdk-root ../ --sm-path ../sourcemod --mms-path ../metamod --enable-optimize
          mkdir css
          mkdir episode1
          # Сборка для CS:S
          cd css
          python ../../configure.py --sdks=css --hl2sdk-root ../../ --sm-path ../../sourcemod --mms-path ../../metamod --enable-optimize
          ambuild
          # Сборка для CS:S v34
          cd ../episode1
          python ../../configure.py --sdks=episode1 --hl2sdk-root ../../ --sm-path ../../sourcemod_1_10 --mms-path ../../metamod_1_10 --enable-optimize
          ambuild
          # move exts
          cd ../..
          mkdir -p out
          cp build/css/package/addons/sourcemod/extensions/* out/
          cp build/episode1/package/addons/sourcemod/extensions/* out/

      - name: Build extension (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          set PYTHONUTF8=1
          mkdir build
          cd build
          mkdir css
          mkdir episode1
          # Сборка для CS:S
          cd css
          python ../../configure.py --sdks=css --hl2sdk-root ../../ --sm-path ../../sourcemod --mms-path ../../metamod --enable-optimize
          ambuild
          # Сборка для CS:S v34
          cd ../episode1
          python ../../configure.py --sdks=episode1 --hl2sdk-root ../../ --sm-path ../../sourcemod_1_10 --mms-path ../../metamod_1_10 --enable-optimize
          ambuild
          # move exts
          cd ../..
          mkdir out
          copy build\css\package\addons\sourcemod\extensions\* out\
          copy build\episode1\package\addons\sourcemod\extensions\* out\

      - name: File List (Linux)
        if: runner.os == 'Linux'
        run: |
          cd .
          ls -la
          echo "dll & so files"
          find . -type f -name '*.so' -or -name '*.dll'

      - name: File List (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd .
          dir /a
          echo dll and so files
          dir /s /b *.so *.dll

      - name: Upload ext
        uses: actions/upload-artifact@v4
        with:
          name: ext-${{ runner.os }}
          path: out
